#!/usr/bin/env sh

# -----------------
# v1
# -----------------
if git diff --name-only origin/main | grep -q "^v1/"; then
  echo "⬆️ test version bump for v1..."
  npm run test --workspace v1
fi

# -----------------
# v2
# -----------------
if git diff --name-only origin/main | grep -q "^v2/"; then
  echo "⬆️ test version bump for v2..."
#   cd v2
#   npx standard-version --no-verify
#   cd ..
    exit 0;
fi