#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Checking for changes in workspaces..."

# Get list of changed files staged for commit
CHANGED=$(git diff --cached --name-only)

# If v1 has changes, bump version
if echo "$CHANGED" | grep -E "^v1/src/|^v1/package.json"; then
  echo "📦 Bumping version for v1..."
  # cd v1 && npx standard-version --workspace v1 --no-verify && cd ../
fi

# If v2 has changes, bump version
if echo "$CHANGED" | grep -E "^v2/src/|^v2/package.json"; then
  echo "📦 Bumping version for v2..."
  # cd v2 && npx standard-version --workspace v2 --no-verify && cd ../
fi
