#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Checking changes in workspaces..."

# v1
if git diff --name-only origin/main | grep -q "^v1/"; then
  echo "⬆️ Running version bump for v1..."
  cd v1
  npx standard-version --no-verify
  cd ..
fi

# v2
if git diff --name-only origin/main | grep -q "^v2/"; then
  echo "⬆️ Running version bump for v2..."
  cd v2
  npx standard-version --no-verify
  cd ..
fi
